#!/usr/bin/env bash

set -eou pipefail

nj=32
stage=-1
stop_stage=100

# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
#
#  - $dl_dir/peoples_speech
#      This directory contains the following files downloaded from
#       https://huggingface.co/datasets/MLCommons/peoples_speech
# 
#     - test
#     - train
#     - validation
#
#  - $dl_dir/musan
#      This directory contains the following directories downloaded from
#       http://www.openslr.org/17/
#
#     - music
#     - noise
#     - speech

dl_dir=$PWD/download

. shared/parse_options.sh || exit 1

# vocab size for sentence piece models.
# It will generate data/lang_bpe_xxx,
# data/lang_bpe_yyy if the array contains xxx, yyy
vocab_sizes=(
  # 5000
  # 2000
  # 1000
  500
)

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare callhome_english manifest"
  # We assume that you have downloaded thecallhome_english corpus
  # to $dl_dir/eng
  mkdir -p data/manifests
  if [ ! -e data/manifests/.callhome_english.done ]; then
    lhotse prepare callhome_english -j $nj $dl_dir/eng data/manifests
    touch data/manifests/.callhome_english.done
  fi
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Preprocess People's Speech manifest"
  mkdir -p data/fbank
  if [ ! -e data/fbank/.preprocess_complete ]; then
    ./local/preprocess_callhome_english.py
    touch data/fbank/.preprocess_complete
  fi
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  log "Stage 3: Compute features for train subset of People's Speech"
  if [ ! -e data/fbank/.callhome_english.done ]; then
    ./local/compute_fbank_callhome_english_splits.py \
      --num-workers $nj \
      --batch-duration 600 \
      --start 0 \
      --num-splits 20
    touch data/fbank/.callhome_english.done
  fi
fi
